### ISSUE TITLE
Check if a variable appears in a formula 

### ISSUE THREAD

**Issue by mikand** [pysmt/pysmt#241]
Right now, we can check if a variable `v` appears in a formula `f` as follows:

``` python
v in f.get_free_variables()
```

we might consider adding the shortcut

``` python
v in f
```

Moreover, this idiom can be used to check if a sub-formula appears in a formula.

**Comment by marcogario** [comment]
For variables: would this be limited to free variables only? E.g.: ``` x in Exists([x], x) == False ```

This is important to  understand the semantics of the extension to subformulae. E.g., 
``` And(x,y) in Exists([x,y], And(x,y) ``` is ```False``` if in the case above we consider only free variables. Is this the expected behavior?

Also, note that most likely we will end up with ``` (x in Not(x)  == True ) and (Not(x) in Not(x) == True)``` . 

Do you have any particular use-case in mind?
