### ISSUE TITLE
Failed assumptions in Boolector.

### ISSUE THREAD

**Issue by alexeyignatiev** [pysmt/pysmt#381]
Hi there!

Is the `Failed` [method](http://fmv.jku.at/boolector/doc/boolector.html#boolector.Boolector.Failed) of Boolector supported in PySMT? If yes, how can one invoke it?

Also, is it possible in general to call a solver (z3, cvc4, yices, btor, etc.) **incrementally** on the same formula using Boolean assumptions `A` and get a subset of unsatisfiable/failed ones `C⊆A` if the formula is unsatisfiable because of `C`?

Thanks,
Alexey

**Comment by marcogario** [comment]
You can always access a feature of a solver directly, although you need to be a bit careful. An example of this is given for mathsat in examples/allsat.py .

In your case:
 ```python
with Solver(name="btor") as s: 
  solver.add_assertion(x)
  solver.solve(Not(x))
  btor_notx = solver.converter.convert(Not(x))
  btor_res = solver.btor.Failed(btor_notx)
  ....
```
You call ```Failed``` on the underlying Boolector instance (of course assuming unsat answer). Since you need to pass Boolector Terms, you need to convert them using the ```Converter``` object associated with the solver. It should not be difficult, and if you get a working example, we can add it to the examples/ directory.


We do not currently support extracting unsat assumptions, mostly because we never needed it! :smile: However, there is an open issue about that (Issue #91) because technically this is part of the SMT-LIB 2.5, so at some point we need to fix it. If you feel like giving it a shot, let us know.

**Comment by 2sev** [comment]
Thanks for the reply!

Does this mean that I need to create a converted version of the formula (in the form of Boolector terms) every time I call the solver? And would it be efficient? The reason I am asking this is that I need to call the solver many times, each time with a different set of assumptions. If the outcome of the solver is `false`, I need to be able extract failed assumptions. So the question is whether calling this `converter` is needed every time or just once or not.

Also, as far as I understand, `Failed` can be called after getting the `false` outcome from the solver call. This seems to be not obvious in your example. Do you call Boolector again after converting the formula into Boolector terms?

**Comment by marcogario** [comment]
Internally, those formulas have already been translated by pySMT, the first time you used them with the given solver. In the example above, ```Not(x)``` was converted internally when calling ```solve```. Calling again the converter is cheap, because it stores internally the association pysmt-term<->solver-term (so you pay a lookup in a map) . Once you get a reference to the boolector term, you can store it and reuse it as many times as you want. Relying on the converter makes this process a bit easier.

If you call ```Solver.solve()``` this will call the underlying solver solve method. You do not need it to call it again. In the example, I did not check for the result of solve(), but you should.

**Comment by 2sev** [comment]
OK, great! Thank you very much for your help! This is exactly what I need. :)

**Comment by 2sev** [comment]
Actually, assumption handling for `btor` in PySMT is done incorrectly. More precisely, if I try to do the following:
```python
from pysmt.shortcuts import Solver, Or, Not, Symbol

with Solver(name='btor') as solver:
    x = Symbol('x')
    y = Symbol('y')
    solver.add_assertion(Or(x, y))
    solver.solve([Not(x), Not(y)])
    btor_notx = solver.converter.convert(Not(x))
    btor_noty = solver.converter.convert(Not(y))
    print solver.btor.Failed(btor_notx, btor_noty)
```
Boolector exits with SIGABRT:
```
[boolector.c] boolector_failed: 'exp' must be an assumption
Abort trap: 6
```
As you may notice, the example is perfectly fine. I have two assumptions under which the formula becomes unsatisfiable, and I want to know which assumptions fail. The reason for the Boolector's failure is how you handle assumptions in `solvers/btor.py`:
```python
    def _solve(self, assumptions=None):
        if assumptions is not None:
            assumption = self.mgr.And(assumptions)
            self._assert_is_boolean(assumption)
            btor_assumption =  self.converter.convert(assumption)
            self.btor.Assume(btor_assumption)
```
Making an `And` term is not correct. Assumptions must be passed to Boolector as a list of terms, e.g. something like this:
```python
    def _solve(self, assumptions=None):
        if assumptions is not None:
            btor_assumptions = [self.converter.convert(a) for a in assumptions]
            self.btor.Assume(*btor_assumptions)
```
Now, if I run the example shown above, I get the correct output: `[True, True]`, because both assumptions cause unsatisfiability.

**Comment by marcogario** [comment]
I think you are right. Could you please open a PR with your fix, and use your example as a regression test? I will have some time next week to check it and merge it. Additionally, I should check if the same issue appears somewhere else.
Thanks.

**Comment by mikand** [comment]
PR #394
