### ISSUE TITLE
printing of terms in SMT-LIBv2 should be easier

### ISSUE THREAD

**Issue by agriggio** [pysmt/pysmt#396]
Currently, it seems that printing of individual terms/formulas in SMT-LIB syntax is rather complicated. There is a `write_smtlib` shortcut, but it has several problems:

- it only works for formulas, not other kind of expressions (e.g. `Plus(Symbol("x"), Int(4))`)
- takes a filename as parameter instead of returning a string
- it prints also declarations and other commands, not just an SMT-LIB representation of the term

We would like to have a `to_smtlib()` function that takes a term and returns a string representation of it. Example:

`assert to_smtlib(Plus(Symbol("x"), Int(4))) == "(+ x 4)"`

**Comment by mikand** [comment]
Here is a snippet to support the feature now, I will create a PR for a proper shortcut ASAP.

```python
from pysmt.smtlib.printers import SmtPrinter
from six.moves import cStringIO

def to_smtlib(f):
    buf = cStringIO()
    p = SmtPrinter(buf)
    p.printer(f)
    res = buf.getvalue()
    buf.close()
    return res


if __name__ == "__main__":
    from pysmt.shortcuts import *
    from pysmt.typing import INT
    assert to_smtlib(Plus(Symbol("x", INT), Int(4))) == "(+ x 4)"
```

**Comment by marcogario** [comment]
Shall this be a shortcut, an option of fnode.serialize(), or a new method
of fnode?

**Comment by mikand** [comment]
I'm leaning towards the second option: ```fnode.serialize(smtlib=True)```.

What do you (both) think?

**Comment by agriggio** [comment]
I think it should be the most obvious thing to do, so +1 for the shortcut version. If you want it to be a method, why not having both? E.g:

```
def to_smtlib(f):
    return f.serialize(smtlib=True)
```

**Comment by marcogario** [comment]
We do not have a thresholded printer for smtlib. I think that overloading
.serialize has no advantage, and makes the statement verbose.
More over, we would need to add the parameter in shortcuts.serialize; if we
add the shortcut to_smtlib, this would mean that we would end up with 2
ways of doing the same thing within shortcuts.

I would go with fnode.to_smtlib.  For symmetry we can add the shortcut too
(since we already have it for serialize), although I think it won't be used
much.

Since this method does not depend on the environment, I see no reason not
to implement it within fnode.

@mikand Assign the ticket to whoever should do this.

**Comment by agriggio** [comment]
shortcuts is where people look for things: if a `to_smtlib` is not in shortcuts, it will be hard to find for newcomers.
Also, please consider printing as DAG when there are shared subterms (maybe the above implementation does that already?)

**Comment by marcogario** [comment]
Yes i agree on the comment on shortcuts: it enhances discoverability.

To print as dag we need to use 'let', otherwise introducing intermediate
define-fun, would mean that this is not a formula but a script, right? I
agree on having this. This should be already implemented somewhere.

I am not sure about which should be the default. I think dag should be the
default, but lets start implementing it without and think a bit more on
when daggification makes sense (eg we could use an approach similar to
thresholding, or activate it only for formulas that are "big").

Please note that dag printing using define-fun is already available in the
printer, but you get a full smtlib script.

**Comment by mikand** [comment]
@marcogario I can take care of this. Let's go with the dedicated shortcut + method and then discuss the details in the PR.

@agriggio You can print a term daggified using lets even now by using ```SmtDagPrinter``` in place of ```SmtPrinter``` in my previous snippet

**Comment by marcogario** [comment]
See PR #399 .
