### ISSUE TITLE
infix operators = and % not recognizable

### ISSUE THREAD

**Issue by cfuxiang** [pysmt/pysmt#398]
Hi,

*Solver used is yices

I try to use `=` and `==` in the equation but 
e.g.
`((h = 1) > 0)` displays invalid syntax for `=` AND
`((h == 1) > 0)` displays the message saying that bool object has no attribute for `==` 

Similarly, % cannot be used in the equation as well.

Is this a bug?

**Comment by mikand** [comment]
Hi, 

this is the expected behavior. Equality is not available as an infix operator because we wanted to allow for easy syntactic comparison of two formulae: f == G returns true if f and g are syntactically identical (in the same environment). 

The modulus operator instead is not yet supported by pysmt (not even in prefix form), we are limited to the linear integer arithmetic with no congruence extensions.

Hope this helps

**Comment by cfuxiang** [comment]
@mikand Thanks for the info.

Does the vanilla yices support the "mod" operator? I think I have seen it last time. Does this "mod" operator behaves the same as %?

**Comment by mikand** [comment]
Unfortunately, I do not know if yices supports it. Both Z3 and mathsat do support it.
