### ISSUE TITLE
Seems like the Einstein example has a mistake.

### ISSUE THREAD

**Issue by frmsaul** [pysmt/pysmt#440]
`# The owner who smokes Blends lives next to the one who keeps cats.
And( Iff(smoke(i, "blends"), Or(pet(i-1, "cats"), pet(i+1, "cats"))) for i in Houses )`
This means that if a person lives next to a cat owner, he must smoke Blends. This is not equivalent to the original statement. Due to this, I feel like the statement is encoded incorrectly. As far as I understand it, it should be:
`And( If(smoke(i, "blends"), Or(pet(i-1, "cats"), pet(i+1, "cats"))) for i in Houses )`
With 'If' instead of 'Iff'. 

[The line as it appears in the example](https://github.com/pysmt/pysmt/blob/f9274a3f07d42832f865ba306ab5881a3574c27e/examples/einstein.py#L123)

**Comment by marcogario** [comment]
Thanks for reporting this. You are correct, in the sense that we use an encoding that is stronger than necessary. In fact, most of the statements could be converted into Implies, instead of Iff. By using the Iff we get a subset of the models we would get with Implies; in other words, if a solution exists for this stronger version of the model, that is also a solution for the weaker version with Implies.

I will take a look on how we can change this model while preserving the goal of the example: explain unsat core extraction.

**Comment by marcogario** [comment]
I had some time to look into this. I changed that part of the example to use the Implies, as I agree it makes more semantic sense. Luckily the rest of the example still makes sense as a way to explain UNSAT cores :).
Thanks for reporting this!

Fixed in #448.

**Comment by frmsaul** [comment]
Thank you for working on this awesome project!
