### ISSUE TITLE
Got ... in printing the formula

### ISSUE THREAD

**Issue by RyanWangGit** [pysmt/pysmt#457]
I'm doing a program verification project that I need the smt solver to solve the constraints. However as I did what the documentation says to print the formula `print(formula)`
I get ... in the formula, Is there a way to fully print it?

For example,
> 2 if q[i]+eta_2>=T_threshold else 0

Would print like

> (^eta_2 = ((T_threshold <= (...[...] + eta_2)) ? 2.0 : 0.0))

**Comment by mikand** [comment]
Hi! Thanks for using PySMT!

The `...` in formula printing is to avoid to convert huge formulae to strings, but you can of course print a formula completely.
 
If the formula is sufficiently small, `print(formula.serialize())` will convert it to a string and print it completely.

If you need to print very large formulae, It is better to avoid the string conversion and use a printer instead.
```python
p = pysmt.printers.HRPrinter(sys.stdout)
p.printer(formula)
```

**Comment by RyanWangGit** [comment]
Thanks for that, is this in the documentation? If not I think it's better to put this in it.

**Comment by RyanWangGit** [comment]
Another minor thing is that, wouldn't `printer.print()` be more reasonable?

**Comment by marcogario** [comment]
- ```.serialize``` should be in the documentation. I think it makes sense once you know why we did it, but otherwise it typically confuse users.
- ```printer.printer``` is for historical reasons. We previously had problems with ```print``` being a keyword. Might be worth taking another look on whether it is possible to make this name more intuitive.

**Comment by marcogario** [comment]
.serialize was documented in the getting started section. I added a code-snippet to make it more apparent.
http://pysmt.readthedocs.io/en/latest/getting_started.html

printer.printer is due to the support for python 2.7. Since ```print``` is a keyword, you cannot use it to as an identifier. While this would be possible by adding  ```from __future__ import print_function``` in python 2.7 code, this import would have to be imported in *every* file using a printer. While the name ```printer``` might be non-intuitive, I think it is still better than requiring to explicitely import the print function.
Hopefully this will change once we drop support for python 2.7 (next year?).

Thanks for the feedback!
