### ISSUE TITLE
NoLogicAvailableError: Logic Detected Logic is not supported

### ISSUE THREAD

**Issue by RyanWangGit** [pysmt/pysmt#462]
I'm currently using z3 as the solver backend and I want to generate a constraint like 

`forall i . q[i] == 0.0`

my code is as follows:

```
symbol_i = shortcuts.Symbol('i', REAL)
ForAll([symbol_i], Equals(Select(Symbol('q', Array(REAL, REAL)), symbol_i), Real(0))
```

But I get 

> NoLogicAvailableError: Logic Detected Logic is not supported

Is there anything wrong with my code for that? I believe Z3 has support for this.

**Comment by mikand** [comment]
This example uses real arithmetic, arrays and quantifiers, so the logic would be "ALRA". Currently, PySMT does not support quantifiers and arrays, so the error message is the expected behavior. 

I think that the problem is in general undecidable, but maybe Z3 has some incomplete technique for this. You can skip the logic check by directly using the solver:
```
with Solver(name="z3") as s:
    s.add_assertion(ForAll([symbol_i], Equals(Select(Symbol('q', ArrayType(REAL, REAL)), symbol_i), Real(0)))
    s.solve() # Returns True on my PC
```

Another thing: some solvers allow to initialize an infinite array to a constant value with a special operators that avoids the use of quantifier. Pysmt supports this with the `Array` shortcut.
Your example simply becomes:
```
Equals(Symbol('q', ArrayType(REAL, REAL)), Array(REAL, Real(0)))
# The array q is initialized to 0 in every index
```

Note that is also possible to initialize arrays by passing an additional dictionary to the `Array` shortcuts:
```
Equals(Symbol('q', ArrayType(REAL, REAL)), Array(REAL, Real(0), {Real(5): Real(8)}))
# The array q is initialized to 0 except for index 5.0 that is set to 8.0
```

HTH

**Comment by RyanWangGit** [comment]
Thanks a lot for the documentations with bypassing the logic checks I can use the solver now.
