### ISSUE TITLE
Module operator is missing

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#47]
Mod operator is missing

**Comment by mikand** [comment]
The problem is that a quantifier elimination in LIA could produce a modular congruence.
We decided to go for an "incomplete" LIA quantifier elimination avoiding the MOD operator that is problematic for almost all the solvers (Only Z3 and partially MathSAT support it).

If a QE in LIA produces a MOD (using Z3) an exeption containing the Z3 expression will be returned
