### ISSUE TITLE
Converting Booleans to Ints?

### ISSUE THREAD

**Issue by sschilli** [pysmt/pysmt#477]
Say I want a constraint that 5 or more of a given set of booleans are true. Is there currently support for such a constraint? I see no way to convert a Bool to an Int which would make this very easy.

**Comment by marcogario** [comment]
The conversion would probably not scale very well. Depending on how many elements you need to take into account, you can try a few things.

In the simplest encoding, you enumerate all valid solutions. This does not scale for more than a dozen elements. Better encoding based on sorting networks are possible and we had a prototype. If you are interested, I can provide you with more info to implement this. 

Otherwise you can use an ite to convert the bool into an integer: Ite(x, Int(1), Int(0))

For bitvectors, there is an operator to convert them into integers. Bv2nat (see https://github.com/pysmt/pysmt/pull/450).
