### ISSUE TITLE
Copy the state / context for incremental solving

### ISSUE THREAD

**Issue by samuelkolb** [pysmt/pysmt#485]
Consider an SMT problem `P` and, after solving it, I want to copy the current solver state / context. The idea is that for every copy, I want to push different assertions `a_1`, ..., `a_n` and solve the modified problems (`P AND a_1`, ..., `P AND a_n`) incrementally. In case it matters, I'd want to do this recursively: for every modified problem, I'd again push different assertions. I am having trouble understanding how I should best realize this using PySMT. My intuition is that it might be feasible by pushing / popping contexts, however, I don't understand how these work. Hopefully, someone could help me out!

**Comment by mikand** [comment]
Hi, thanks for using pysmt!

The simplest way to do this is to use solving under assumptions. Many solvers implement this feature natively, you can declare a formula with several assertions and then incrementally verify the formula under different assumptions.

Here is a simple example:
```python
from pysmt.shortcuts import *

x, y = (Symbol(n, REAL) for n in "xy")
f1 = GE(x, Real(0))
f2 = GE(y, Real(0))

a, b = (Symbol(n, BOOL) for n in "ab")

with Solver(logic="QF_LRA") as s:
    s.add_assertion(LT(Plus(x, y), Real(0))) # a fixed part of the formula
    s.add_assertion(Implies(a, f1)) # add assertion A1: a -> f1
    s.add_assertion(Implies(b, f2)) # add assertion A2: b -> f2

    # check with only A1
    c = s.solve(assumptions=[a])
    print('[a] is %s' % ('sat' if c else 'unsat'))

    # check with only A2
    c = s.solve(assumptions=[b])
    print('[b] is %s' % ('sat' if c else 'unsat'))

    # check with both A1 and A2
    c = s.solve(assumptions=[a, b])
    print('[a, b] is %s' % ('sat' if c else 'unsat'))
```
As you can see, you can declare your formula using implications to make it trivially sat (if no assumptions are specified, both `a` and `b` can be set to false).

If you want, instead of using the `with` statement, you can manually create and destroy the solver to pass it around to (possibly recursive) functions:
```python
from pysmt.shortcuts import *

def f(s, assumptions):
    c = s.solve(assumptions=assumptions)
    print('%s is %s' % (assumptions, ('sat' if c else 'unsat')))

x, y = (Symbol(n, REAL) for n in "xy")
f1 = GE(x, Real(0))
f2 = GE(y, Real(0))

a, b = (Symbol(n, BOOL) for n in "ab")

s = Solver(logic="QF_LRA")
s.add_assertion(LT(Plus(x, y), Real(0))) # a fixed part of the formula
s.add_assertion(Implies(a, f1)) # add assertion A1: a -> f1
s.add_assertion(Implies(b, f2)) # add assertion A2: b -> f2

f(s, [a]) # check with only A1
f(s, [b]) # check with only A2
f(s, [a, b]) # check with both A1 and A2

s.exit() # Destroy the solver instance
```
Finally, note that it is not necessary to do all the `add_assertion`''s beforehand: you can do them as needed as long as you do all the relevant assertions before calling `solve()` function.

Let me know if you need further clarifications.

**Comment by samuelkolb** [comment]
Thanks for your fast and elaborate answer! Using your method, I think my problem would be encoded similarly to this (omitting the initialization etc):

```python
def f(s, assumptions, ...):
  c = s.solve(assumptions=assumptions)
  assertion = calculate_next_assertion(s, ...)
  var = Symbol("v{}".format(len(assumptions)), BOOL)
  s.add_assertion(Iff(var, assertion))
  f(s, assumptions + [var], ...)
  f(s, assumptions + [~var], ...)
```

Will this be the most efficient way to encode the problem? Thanks, btw, for your work on PySMT, it has been very useful!

**Comment by mikand** [comment]
This schema should work, but you need to be very careful with the naming of the assertions, because the solver is unique so if two branches use the same variable name for different assumptions you are in trouble. (My suggestion is to give a unique name using a counter instead of relying on the size of the assumptions, because when you branch the size could happen twice).

Concerning the efficiency, this could be a good technique but the drawback is that the solver never forgets an assertion even if you are sure it will never used again. You could use the stack-based incrementality (i.e. `s.push()` and `s.pop()` methods) that allow you to forget a piece of the formula, but solving under assumptions often works well anyway. 

Here is a minimal example:
```python
with Solver(logic="QF_LRA") as s:
    s.add_assertion(LT(Plus(x, y), Real(0))) # a fixed part of the formula
    s.push()
    s.add_assertion(f1) # add assertion A1: f1
    s.solve() # solves for A1 only
    s.add_assertion(f2) # add assertion A2: f2
    s.solve() # solves for both A1 and A2
    s.pop() # resets the state to the fixed assertion only
    s.add_assertion(f2) # re-add assertion A2: f2
    s.solve() # solves for A2 only
```

HTH

**Comment by samuelkolb** [comment]
Thanks, I amended the code in my example to reflect that you should always choose a unique name. I see how the push / pop approach could work for a depth first approach. For a breadth-first search the assumptions provide an alternative way.

**Comment by mikand** [comment]
Yes, with the assumptions method you can in principle declare all the assertions first and then explore any subset of them in any order.

**Comment by samuelkolb** [comment]
Thanks!
