### ISSUE TITLE
PysmtTypeError when reusing symbols in SMT-LIB define-fun

### ISSUE THREAD

**Issue by yoni206** [pysmt/pysmt#498]
In the following SMT-LIB definitions, I am using `n` as an Int parameter for `f` and as a Real parameter for `g`:
```
(define-fun f ((n Int)) Int n)
(define-fun g ((n Real)) Real n)
```
This yields PysmtTypeError, saying: `Trying to redefine symbol 'n' with a new type. Previous type was 'Int' new type is 'Real'`.

This should not happen - according to the [standard](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf) (p. 62), `(define-fun f ((n Int)) n)` is equivalent to:
```
(declare-fun f ((n Int) n)
(assert (forall ((n Int)) (= (f n) n)))
```
And so there shouldn't be a problem re-using n.

To reproduce:
`python tmp.py` for `tmp.py` with the following content:

```
from pysmt.smtlib.parser import SmtLibParser
import os

def main():
    smtlib_script = '\n'.join(['(define-fun f ((n Int)) Int n)', '(define-fun g ((n Real)) Real n)'])
    tmp_file_name = "tmp.smt2"
    tmp_file = open(tmp_file_name, 'w')
    tmp_file.write(smtlib_script)
    tmp_file.close()
    parser = SmtLibParser()
    script = parser.get_script_fname(tmp_file_name)
    os.remove(tmp_file_name)

if __name__ == "__main__":
    main()
```

**Comment by marcogario** [comment]
Hi, thanks for reporting this.

I agree that the expression should be parsed correctly. As you probably saw, in pySMT we have a strong link between a symbol and its type. In the context of the define-fun, the n is a parameter and therefore could be replaced internally by something else. If we replace it, however, we need to keep track of how to map the occurrences of n in the expression to the new symbol. If I remember correctly, this was the point of having the bind/unbind methods, but @mikand can probably answer this better.

I quickly looked in the change that you did, and it is not clear to me how this is addressing the problem.  To me, it seems that the call to _get_quantified_var will simply create a new fresh variable, and then the parsing of the expression will use the previous declaration of n (although this should throw a typeerror, I think).

Can you extend your test to make sure that the result of the parsing is actually what you expect?

You can use a cStringIO instead of creating a temporary file. In test_smtlibscript.py we do this quite often, so you should find examples there.

**Comment by mikand** [comment]
Hi @yoni206 
indeed you found a bug. The point there is that we store in the environment a formula associated with the `define-fun` name that enters the pysmt environment associated with the parser. Hence, we cannot have two formulae with the two variables with the same name and different type.

Using `_get_quantified_var` instead of `_get_var` should indeed fix the problem to some extent, but (also in the case of quantifiers) it is possible that the name selected by `FreshSymbol` within  `_get_quantified_var` will be declared later (e.g. by a `define-fun`) causing a later spurious error.

A more principled solution would be to construct the formulae within the `define-fun`s using a clean pysmt environment with a fresh formula manager. Then, when the function is applied the formula is substituted and contextualized in the original environment.

A maybe more practical solution is to use the `FreshSymbol` approach by choosing a better prefix template (right now we simply append a number after the original variable name) that we assume is not usable in elsewhere (e.g. everything beginning with two underscores is private to pysmt).

@marcogario What do you think. Probably in the short term using a more unlikely template like "___%d" and using `_get_quantified_var` should fix the problem for any practical purpose.

**Comment by marcogario** [comment]
If you want to go the hard way, I think a unicode string would be harder to match :P

At a more general level, if we could rename FreshSymbols after creation, this would be the best way to proceed. 1) Create freshsymbol with weird template 2) detect that there is a valid symbol with weird template 3) rename previous freshsymbol with a different template 4) resume your parsing. AFAIR our hasing is based on the FNode id, not on the name, thus renaming an FNode should be possible.

For now, I think it is ok just to change the template. 

However, don't we need the loop after the expression has been parsed? I think this is necessary to avoid that other occurrences of n are mapped to the new freshsymbol. @yoni206 feel free to open a PR, it is much easier to provide feedback on a PR than having to jump to a different codebase. @mikand can you take charge of this review?

**Comment by mikand** [comment]
- Unicode could be dangerous: pysmt supports it no problem, but maybe solvers have problems with that?

- No, " loop after the expression has been parsed" is not needed because the name 'n' would be mapped to the formal argument by the name-binding in the cache of the parser. See https://github.com/pysmt/pysmt/blob/master/pysmt/smtlib/parser/parser.py#L1176

- Sure, I can take charge of this review.

**Comment by yoni206** [comment]
See you at #502 :)
