### ISSUE TITLE
Patches in python package

### ISSUE THREAD

**Issue by marcogario** [pysmt/pysmt#54]
We are currently not distributing the patches in the python package.

After looking better into python packaging, I realized that this is a bit messy. I see two options:

1. Move patches within the package (pysmt/patches). This has the advantage that the patches are stored in a well-known location (within the package) and should be cross-platform. Although I don't like the idea of having the patches in the pkg source code.

2. Embed the patches in install.py during pkg creation (setup.py). This is unorthodox, but has the advantage that the patches are easy to find by install.py (that is also the _only_ file needing them), and we do not pollute the source-tree.

@mikand What do you think? I have a demo for 1. I wanted to get your feedback before trying 2 (that should be easy -> gzip + BaseEncode)

**Comment by mikand** [comment]
I also see a third way (a bit cleaner maybe). Since the patches are not specific for pysmt, but are useful to use the solvers via python, we could create a git repo or put them online. ```install.py``` can then download the patches from the repo. This is also in the spirit of "You install the binding, pysmt abstracts them".

Anyway, between 1 and 2 I  would go with 2...

**Comment by marcogario** [comment]
Only issue with 3 is that we need to keep them in-sync. But I see your
point on keeping them "outside" of pysmt. I am gonna try that solution.

**Comment by marcogario** [comment]
Created repo pysmt/solvers_patches to collect all patches from the solvers.
In install.py we define the revision of the patch. **Note** this needs to be updated manually if we change/add a patch.

**Comment by marcogario** [comment]
PR #55
