### ISSUE TITLE
Error when installing MathSAT through pysmt-install on Mac with python 3.7

### ISSUE THREAD

**Issue by samuelkolb** [pysmt/pysmt#604]
When trying to install MathSat through

    pysmt-install --msat

I get the following error:

    running build_ext
    Traceback (most recent call last):
      File ".../env/bin/pysmt-install", line 10, in <module>
        sys.exit(main())
      File ".../env/lib/python3.7/site-packages/pysmt/cmd/install.py", line 261, in main
        installer.install(force_redo=options.force_redo)
      File ".../env/lib/python3.7/site-packages/pysmt/cmd/installers/base.py", line 150, in install
        self.move()
      File ".../env/lib/python3.7/site-packages/pysmt/cmd/installers/msat.py", line 105, in move
        soname = glob.glob(self.bindings_dir + "/_mathsat*.so")[0]
    IndexError: list index out of range

I installed pysmt in a virtualenv and running python 3.7 (on a Mac).

**Comment by samuelkolb** [comment]
Do you guys have any idea on why installing MathSat doesn't work?

**Comment by mikand** [comment]
Hi @samuelkolb,

sorry for the delay, for me this is an exceptionally busy period.

In general MathSAT should work on MacOSX (see our CI: https://dev.azure.com/micheliandrea/PySMT/_build/results?buildId=224).

The error you posted, seems to indicate that when extracting the archive, the ".so" library is missing, but this does not seem to happen on our CI and unfortunately I do not own an OSX machine. Can you try to manually remove any mathsat-related python files from `~/.smt_solvers` and your `site-packages` and retry? Also, you might try to search your HD for a `_mathsat*` file, maybe the issue is that SWIG is giving a different name or extension on your system...

**Comment by Ahmed-anwar** [comment]
@samuelkolb 
I had a similar problem when I was trying to install mathsat on my linux machine, I always got: 
`running build_ext`

then nothing happened. 

I tried deleting everything in `~/.smt_solvers/msat/ ` and ran `pysmt-install --msat` again and it worked.

**Comment by gajdikuka** [comment]
> @samuelkolb
> I had a similar problem when I was trying to install mathsat on my linux machine, I always got:
> `running build_ext`
> 
> then nothing happened.
> 
> I tried deleting everything in `~/.smt_solvers/msat/ ` and ran `pysmt-install --msat` again and it worked.

Where is that folder exactly? I am using Anaconda3
