### ISSUE TITLE
Unexpected solution to an ILP instance encoded as a logical formula

### ISSUE THREAD

**Issue by akumm2k** [pysmt/pysmt#735]
```python
"""
This encodes the following ILP using logical formula

    y <= x - 1
    y >= -2x + 2
    minimize x

The constraints can be encoded directly.
For the objective function, we may have
    exists xm for all x, such that
    ... constraints(x) ...
    and 
    ... constraints(xm) ...
    imply xm <= x

The model value for xm should be 1
"""

from pysmt.shortcuts import (
    Symbol, FreshSymbol,
    Solver, qelim,
    GE, LE, GT, LT, Equals, NotEquals,
    ForAll, Exists, 
    And, Or, Not, Iff, Implies, Min,
    Plus, Minus, Times,
    Real, Int,
    get_model,
)
import pysmt.typing as pysmt_type

def constraints(x: pysmt_type.INT):
    y = Symbol('y', pysmt_type.INT)
    return (y <= x - Int(1)).And(y >= Int(-2) * x + Int(2))

xm, x = Symbol('xm', pysmt_type.INT), Symbol('x', pysmt_type.INT)
dummy = Symbol('d', pysmt_type.INT)

formula = Exists([xm],
    ForAll([x], 
        Implies(
            constraints(xm).And(constraints(x))
            , GE(x, xm)
        )
    ).And(Equals(dummy, Int(1)))
)
```

Here is what I get, running it in interactive mode.
```
>>> x = qelim(formula)
>>> x
(d = 1)
>>> m = get_model(formula)
>>> m.get_value(xm)
0
```
Could you please clarify if I am doing something wrong here?

**Comment by mikand** [comment]
@akumm2k thanks for using pysmt.

The error seems to be in the formula, what you want to write is the following:
```
import pysmt.typing as pysmt_type
from pysmt.shortcuts import GE, And, ForAll, Implies, Int, Symbol, get_model


def constraints(x: pysmt_type.INT):
    y = Symbol('y', pysmt_type.INT)
    return (y <= x - Int(1)).And(y >= Int(-2) * x + Int(2))

xm, x = Symbol('xm', pysmt_type.INT), Symbol('x', pysmt_type.INT)

formula = And(constraints(xm), ForAll([x],
        Implies(
            constraints(x)
            , GE(x, xm)
        )
    ))

m = get_model(formula)
print(m.get_value(xm))
```

In your version, you basically quantified out all the varibles, instead you need to leave some free variables as SMT's job is to find an assignment (or interpretation if you have functions) for the free variables in the formula. Moreover, I had to move the constraints over `xm` outside of the implication, because you want to ensure that all the models of `xm` fulfill the constraints (leavinf them as implicant allows the formula to accept any value for `xm` violating the constraints, because `false` implies anything).

Hope this helps, moreover let me point out that quantification is an extremely costly procedure (you are basically finding all the optimal solutions at once with this encoding) and there are some SMT solvers which support optimization natively. Pysmt supports optimization expreimentally in the optimization branch: https://github.com/pysmt/pysmt/pull/439.
