### ISSUE TITLE
Substitution issue for ForAll using MGSubstituter

### ISSUE THREAD

**Issue by SSharath-Kumar** [pysmt/pysmt#746]
Unable to perform substitution on ForAll expressions using MGSubstituter

**Comment by mikand** [comment]
@SSharath-Kumar can you post a code snippet reproducing the problem?

**Comment by SSharath-Kumar** [comment]
```
from pysmt.shortcuts import Symbol, ForAll, get_env
from pysmt.substituter import MGSubstituter
from pysmt.typing import INT


varA = Symbol("A", INT)
varB = Symbol("B", INT)
varC = Symbol("C", INT)
f_exp = ForAll([varA,varB], varA > varB)
mgs = MGSubstituter(get_env())
print(mgs.substitute(f_exp,{varA: varC}))
```

**Comment by mikand** [comment]
@SSharath-Kumar this is the expected behavior, because in logic, the formula (\forall varA . \forall varB . varA > varB) has no free variables and the substuter can only change free variables (or terms defined over free variables)...

Consider the case   `f_exp = And(varA< 2, ForAll([varA,varB], varA > varB)`. In this case you would get `And(varC< 2, ForAll([varA,varB], varA > varB)`: the substituter actively does quite some work to distinguish bound variables from free variables.

If you need to rename the variable bounded by a quantifier, you need to pass the formula and rename it manually, because in gneral you might have situations like `\forall x . x > 2 and \forall x . x < 3`...
